name: CI

on: [push, pull_request]

jobs:
  # This job downloads substrate contract node from parity and runs it with the IT
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: 'paritytech/substrate-contracts-node'
          version: 'tags/v0.16.0'
          file: "substrate-contracts-node-linux.tar.gz"
          target: "node/substrate-contracts-node-linux.tar.gz"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract some files
        run: 7z x node/substrate-contracts-node-linux.tar.gz

      - uses: andstor/file-existence-action@v1
        name: Check file existence
        id: check_files
        with:
          files: "node/artifacts/substrate-contracts-node-linux/substrate-contracts-node"

      - name: File exists
        if: steps.check_files.outputs.files_exists == 'true'
        run: echo "It exists !"

      - name: Extract some files
        run: 7z x node/substrate-contracts-node-linux.tar.gz

      - uses: actions/checkout@v2
      - name: Run script file
        run: |
          chmod +x ./scripts/node.sh
          ./scripts/node.sh
        shell: bash
