name: CI

on: [push, pull_request]

jobs:
  # This job downloads substrate contract node from parity and runs it with the IT
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: 'paritytech/substrate-contracts-node'
          version: 'tags/v0.16.0'
          regex: true
          file: "substrate-contracts-node-linux.tar.gz"
          token: ${{ secrets.GITHUB_TOKEN }}
